channels:
- conda-forge
dependencies:
- python=3.10.5
- pip<=24.0
- pip:
  - mlflow==2.11.3
  - cloudpickle==3.0.0
  - numpy==1.26.4
  - packaging==23.0
  - psutil==5.9.4
  - pyyaml==6.0.1
  - scikit-learn==1.4.2
  - scipy==1.13.0
name: mlflow-env
